"""Replay a recorded run through the same Backend interface as a live provider.

This is the fallback when no OpenAI key is present. It is not a mock in the
usual sense: the text it serves was generated by a model and recorded, so the
pipeline downstream of it behaves exactly as it does live. What is *not* real is
the latency, which is modelled, and the fact that nothing is being decided now.

Two rules keep it honest:

* It serves responses in the order the pipeline asks for them, keyed by the
  schema requested. If the pipeline changes shape, the replay runs out of
  recorded turns and raises rather than inventing one.
* Every run it produces is labelled `cached` all the way into the results table,
  so a recorded run can never be mistaken for a measurement.
"""
from __future__ import annotations

import json
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Type

from crisis_debate.schemas import (
    Argument,
    ArgumentJudgment,
    Claim,
    CriterionScore,
    Option,
    PackageItem,
    Recommendation,
    RoundJudgment,
    Scenario,
)

CACHE_DIR = Path(__file__).resolve().parents[1] / "cached"


class CacheExhausted(RuntimeError):
    """The pipeline asked for more turns than were recorded."""


def available() -> List[str]:
    return sorted(p.stem for p in CACHE_DIR.glob("*.json"))


def load_cache(scenario_id_or_name: str) -> Dict[str, Any]:
    p = CACHE_DIR / f"{scenario_id_or_name}.json"
    if not p.exists():
        for cand in CACHE_DIR.glob("*.json"):
            if json.loads(cand.read_text(encoding="utf-8")).get("scenario_id") == scenario_id_or_name:
                p = cand
                break
        else:
            raise FileNotFoundError(f"no recorded run for {scenario_id_or_name!r}; have {available()}")
    return json.loads(p.read_text(encoding="utf-8"))


def _items(pkg: Dict[str, str]) -> List[PackageItem]:
    return [PackageItem(issue=k, option=v) for k, v in pkg.items()]


@dataclass
class CachedBackend:
    """Serves recorded turns in pipeline order.

    `speed` replays the recorded latency: 0 is instant (the default, and what
    tests use), 1 is real time, 4 is four times faster than the recording.
    """

    scenario: Scenario
    cache: Dict[str, Any]
    speed: float = 0.0
    usage: Dict[str, int] = field(default_factory=lambda: {"input": 0, "output": 0, "calls": 0})
    is_cached: bool = True
    _arg: int = 0
    _judge: int = 0
    _rec: int = 0

    @classmethod
    def for_scenario(cls, scenario: Scenario, speed: float = 0.0) -> "CachedBackend":
        return cls(scenario=scenario, cache=load_cache(scenario.scenario_id), speed=speed)

    def _sleep(self, ms: int) -> None:
        if self.speed > 0 and ms:
            time.sleep(ms / 1000.0 / self.speed)

    def parse(self, *, system: str, user: str, output_format: Type, max_tokens: int = 16000):
        self.usage["calls"] += 1

        if output_format is Argument:
            flat = [t for rnd in self.cache["rounds"] for t in rnd]
            if self._arg >= len(flat):
                raise CacheExhausted(
                    f"recorded run has {len(flat)} argument turns; the pipeline asked for "
                    f"{self._arg + 1}. Record more rounds or run with fewer."
                )
            t = flat[self._arg]; self._arg += 1
            self._sleep(t.get("latency_ms", 0))
            return Argument(country=t["country"], position=t["position"],
                            key_claims=[Claim(claim=t["position"], evidence="recorded run")],
                            concessions=[t["concession"]], red_lines=[],
                            proposed_package=_items(t["package"]))

        if output_format is RoundJudgment:
            rec = self.cache["judge"]
            if self._judge >= len(rec):
                raise CacheExhausted(f"recorded run has {len(rec)} judged rounds; asked for {self._judge + 1}.")
            j = rec[self._judge]; self._judge += 1
            self._sleep(j.get("latency_ms", 0))
            return RoundJudgment(
                round_index=j["round_index"],
                judgments=[ArgumentJudgment(
                    country=x["country"],
                    scores=[CriterionScore(criterion=k, score=v, justification=x["summary"])
                            for k, v in x["scores"].items()],
                    summary=x["summary"]) for x in j["judgments"]],
                unaddressed_tradeoffs=j["unaddressed"])

        if output_format is Recommendation:
            # The baseline conditions ask for a recommendation without any
            # debate having happened, so they get the recorded baseline; the
            # debate conditions get the recorded synthesis.
            src = self.cache["baseline"] if self._arg == 0 else self.cache["recommendation"]
            self._rec += 1
            self._sleep(src.get("latency_ms", 0))
            return Recommendation(
                focus_country=self.scenario.focus_country,
                options=[Option(condition=o["condition"], action=o["action"],
                                priority_tag=o["priority_tag"],
                                requires_concession="see rationale",
                                principal_risk="see rationale") for o in src["options"]],
                rationale=src["rationale"], recommended_package=_items(src["package"]))

        raise AssertionError(f"no recorded response for {output_format!r}")
